package identity

// API Version: v8_0

type AaaServer struct {
	// ID
	// the identifier of the AAA server
	ID *string `json:"id,omitempty"`

	// Name
	// the identifier of the AAA server
	Name *string `json:"name,omitempty"`
}

type AaaServerList struct {
	FirstIndex *int `json:"firstIndex,omitempty"`

	HasMore *bool `json:"hasMore,omitempty"`

	List []*AaaServer `json:"list,omitempty"`

	TotalCount *int `json:"totalCount,omitempty"`
}

type AuthenticationServerConfig struct {
	// AUTHENTICATIONSERVERID
	// Authentication server id
	AUTHENTICATIONSERVERID *string `json:"AUTHENTICATION_SERVER_ID,omitempty"`

	// AUTHENTICATIONSERVERNAME
	// Authentication server name
	AUTHENTICATIONSERVERNAME *string `json:"AUTHENTICATION_SERVER_NAME,omitempty"`

	// AUTHENTICATIONSERVERTYPE
	// Authentication server type
	AUTHENTICATIONSERVERTYPE *string `json:"AUTHENTICATION_SERVER_TYPE,omitempty"`

	// ID
	// server id
	ID *string `json:"id,omitempty"`

	// Local
	// Is local server
	Local *bool `json:"local,omitempty"`

	// Name
	// server name
	Name *string `json:"name,omitempty"`

	// Type
	// server type
	Type *string `json:"type,omitempty"`
}

type CountryList struct {
	FirstIndex *int `json:"firstIndex,omitempty"`

	HasMore *bool `json:"hasMore,omitempty"`

	List []*CountrySummary `json:"list,omitempty"`

	TotalCount *int `json:"totalCount,omitempty"`
}

type CountrySummary struct {
	// CountryName
	// Full name of country
	CountryName *string `json:"countryName,omitempty"`

	// CountryShortName
	// Short name of country
	CountryShortName *string `json:"countryShortName,omitempty"`
}

type CreateIdentityGuestPass struct {
	// AutoGeneratedPassword
	// Pass generation
	AutoGeneratedPassword *bool `json:"autoGeneratedPassword,omitempty"`

	// DomainID
	// Domain Id
	DomainID *string `json:"domainId,omitempty"`

	GuestName *string `json:"guestName,omitempty"`

	MaxDevices *MaxDevices `json:"maxDevices,omitempty"`

	// NumberOfPasses
	// Number of passes
	NumberOfPasses *int `json:"numberOfPasses,omitempty"`

	// PassEffectSince
	// Pass effective since
	PassEffectSince *string `json:"passEffectSince,omitempty"`

	// PassUseDays
	// Expire new guest pass if not used within
	PassUseDays *int `json:"passUseDays,omitempty"`

	PassValidFor *PassValidFor `json:"passValidFor,omitempty"`

	// PassValue
	// Pass value
	PassValue *string `json:"passValue,omitempty"`

	// Remarks
	// Remarks
	Remarks *string `json:"remarks,omitempty"`

	SessionDuration *SessionDuration `json:"sessionDuration,omitempty"`

	WLAN *common.GenericRef `json:"wlan,omitempty"`

	Zone *common.GenericRef `json:"zone,omitempty"`
}

type CreateIdentityUserRole struct {
	Description *string `json:"description,omitempty"`

	// DomainID
	// Domain Id
	DomainID *string `json:"domainId,omitempty"`

	MaxDevices *MaxDevices `json:"maxDevices,omitempty"`

	Name *string `json:"name,omitempty"`

	UserTrafficProfile *common.GenericRef `json:"userTrafficProfile,omitempty"`

	// VlanID
	// vlan id
	VlanID *int `json:"vlanId,omitempty"`

	VlanPooling *common.GenericRef `json:"vlanPooling,omitempty"`
}

type CreateSubscriptionPackage struct {
	Description *string `json:"description,omitempty"`

	// DomainID
	// Domain Id
	DomainID *string `json:"domainId,omitempty"`

	// ExpirationInterval
	// Expiration interval
	ExpirationInterval *string `json:"expirationInterval,omitempty"`

	// ExpirationValue
	// Expiration value
	ExpirationValue *int `json:"expirationValue,omitempty"`

	Name *string `json:"name,omitempty"`
}

type CreateUser struct {
	// Address
	// Address
	Address *string `json:"address,omitempty"`

	// City
	// City
	City *string `json:"city,omitempty"`

	// CountryName
	// Country
	CountryName *string `json:"countryName,omitempty"`

	// CountryShortName
	// Country
	CountryShortName *string `json:"countryShortName,omitempty"`

	// DomainID
	// Domain ID
	DomainID *string `json:"domainId,omitempty"`

	// Email
	// Email
	Email *string `json:"email,omitempty"`

	// FirstName
	// First name
	FirstName *string `json:"firstName,omitempty"`

	// IsDisabled
	// Is Disabled
	IsDisabled *string `json:"isDisabled,omitempty"`

	// LastName
	// Last Name
	LastName *string `json:"lastName,omitempty"`

	// Password
	// Password
	Password *string `json:"password,omitempty"`

	// Phone
	// Phone
	Phone *string `json:"phone,omitempty"`

	// Remark
	// Remark
	Remark *string `json:"remark,omitempty"`

	// State
	// State
	State *string `json:"state,omitempty"`

	SubscriberPackage *common.GenericRef `json:"subscriberPackage,omitempty"`

	// UserName
	// User Name
	UserName *string `json:"userName,omitempty"`

	// ZipCode
	// Zip Code
	ZipCode *string `json:"zipCode,omitempty"`
}

type DeleteBulk struct {
	IDList common.IDList `json:"idList,omitempty"`
}

type IdentityGuestPassConfiguration struct {
	// AutoGeneratedPassword
	// Pass generation
	AutoGeneratedPassword *bool `json:"autoGeneratedPassword,omitempty"`

	// DomainID
	// identifier of the domain
	DomainID *string `json:"domainId,omitempty"`

	// ExpirationDate
	// Expiration date and time
	ExpirationDate *string `json:"expirationDate,omitempty"`

	// GeneratedOn
	// Generated date and time
	GeneratedOn *string `json:"generatedOn,omitempty"`

	GuestName *string `json:"guestName,omitempty"`

	// ID
	// ID of the identity guest pass
	ID *string `json:"id,omitempty"`

	// Key
	// Identifier of the identity guest pass
	Key *string `json:"key,omitempty"`

	MaxDevices *MaxDevices `json:"maxDevices,omitempty"`

	// PassEffectSince
	// Pass effective since
	PassEffectSince *string `json:"passEffectSince,omitempty"`

	// PassUseDays
	// Expire new guest pass if not used within
	PassUseDays *int `json:"passUseDays,omitempty"`

	PassValidFor *PassValidFor `json:"passValidFor,omitempty"`

	// Remarks
	// Remarks
	Remarks *string `json:"remarks,omitempty"`

	SessionDuration *SessionDuration `json:"sessionDuration,omitempty"`

	// Ssid
	// SSID
	Ssid *string `json:"ssid,omitempty"`

	// UserID
	// user ID of the identity guest pass
	UserID *string `json:"userId,omitempty"`

	WLAN *common.GenericRef `json:"wlan,omitempty"`

	// WLANRestrition
	// Wlan description
	WLANRestrition *string `json:"wlanRestrition,omitempty"`

	Zone *common.GenericRef `json:"zone,omitempty"`
}

type IdentityGuestPassList struct {
	Extra *common.RBACMetadata `json:"extra,omitempty"`

	FirstIndex *int `json:"firstIndex,omitempty"`

	HasMore *bool `json:"hasMore,omitempty"`

	List []*IdentityGuestPassConfiguration `json:"list,omitempty"`

	TotalCount *int `json:"totalCount,omitempty"`
}

type IdentityList struct {
	Extra *common.RBACMetadata `json:"extra,omitempty"`

	FirstIndex *int `json:"firstIndex,omitempty"`

	HasMore *bool `json:"hasMore,omitempty"`

	List []*IdentityListType `json:"list,omitempty"`

	TotalCount *int `json:"totalCount,omitempty"`
}

type IdentityListType struct {
	// CreateDateTime
	// Timestamp of being created
	CreateDateTime *int `json:"createDateTime,omitempty"`

	// CreatorID
	// Creator ID
	CreatorID *string `json:"creatorId,omitempty"`

	// CreatorUsername
	// Creator Name
	CreatorUsername *string `json:"creatorUsername,omitempty"`

	Description *string `json:"description,omitempty"`

	// DomainID
	// identifier of the domain
	DomainID *string `json:"domainId,omitempty"`

	// ID
	// Identifier of the service
	ID *string `json:"id,omitempty"`

	MaxDevices *MaxDevices `json:"maxDevices,omitempty"`

	// ModifiedDateTime
	// Timestamp of being modified
	ModifiedDateTime *int `json:"modifiedDateTime,omitempty"`

	// ModifierID
	// Modifier ID
	ModifierID *string `json:"modifierId,omitempty"`

	// ModifierUsername
	// Modifier Name
	ModifierUsername *string `json:"modifierUsername,omitempty"`

	Name *string `json:"name,omitempty"`

	UserTrafficProfile *common.GenericRef `json:"userTrafficProfile,omitempty"`

	// VlanID
	// vlan id
	VlanID *int `json:"vlanId,omitempty"`

	VlanPooling *common.GenericRef `json:"vlanPooling,omitempty"`
}

type IdentityUserRole struct {
	// CreateDateTime
	// Timestamp of being created
	CreateDateTime *int `json:"createDateTime,omitempty"`

	// CreatorID
	// Creator ID
	CreatorID *string `json:"creatorId,omitempty"`

	// CreatorUsername
	// Creator Name
	CreatorUsername *string `json:"creatorUsername,omitempty"`

	Description *string `json:"description,omitempty"`

	// ID
	// the identifier of the object
	ID *string `json:"id,omitempty"`

	MaxDevices *MaxDevices `json:"maxDevices,omitempty"`

	// ModifiedDateTime
	// Timestamp of being modified
	ModifiedDateTime *int `json:"modifiedDateTime,omitempty"`

	// ModifierID
	// Modifier ID
	ModifierID *string `json:"modifierId,omitempty"`

	// ModifierUsername
	// Modifier Name
	ModifierUsername *string `json:"modifierUsername,omitempty"`

	Name *string `json:"name,omitempty"`

	UserTrafficProfile *common.GenericRef `json:"userTrafficProfile,omitempty"`

	// VlanID
	// vlan id
	VlanID *int `json:"vlanId,omitempty"`

	VlanPooling *common.GenericRef `json:"vlanPooling,omitempty"`
}

type IdentityUserSummary struct {
	// CreatedOn
	// Created on
	CreatedOn *string `json:"createdOn,omitempty"`

	DisplayName *string `json:"displayName,omitempty"`

	// DomainID
	// identifier of the domain
	DomainID *string `json:"domainId,omitempty"`

	// ID
	// Identifier of the identity user
	ID *string `json:"id,omitempty"`

	// IsDisabled
	// Is disalbed
	IsDisabled *string `json:"isDisabled,omitempty"`

	// UserName
	// User Name
	UserName *string `json:"userName,omitempty"`

	// UserSource
	// User Source
	UserSource *string `json:"userSource,omitempty"`

	// UserType
	// User Type
	UserType *string `json:"userType,omitempty"`
}

type ImportIdentityGuestPass struct {
	// DomainID
	// Domain Id
	DomainID *string `json:"domainId,omitempty"`

	MaxDevices *MaxDevices `json:"maxDevices,omitempty"`

	// PassEffectSince
	// Pass effective since
	PassEffectSince *string `json:"passEffectSince,omitempty"`

	// PassUseDays
	// Expire new guest pass if not used within
	PassUseDays *int `json:"passUseDays,omitempty"`

	PassValidFor *PassValidFor `json:"passValidFor,omitempty"`

	SessionDuration *SessionDuration `json:"sessionDuration,omitempty"`

	WLAN *common.GenericRef `json:"wlan,omitempty"`

	Zone *common.GenericRef `json:"zone,omitempty"`
}

type MaxDevices struct {
	// MaxDevicesAllowed
	// Max devices allowed
	MaxDevicesAllowed *string `json:"maxDevicesAllowed,omitempty"`

	// MaxDevicesNumber
	// max devices number
	MaxDevicesNumber *int `json:"maxDevicesNumber,omitempty"`
}

type ModifyIdentityUserRole struct {
	Description *string `json:"description,omitempty"`

	// DomainID
	// Domain Id
	DomainID *string `json:"domainId,omitempty"`

	// ID
	// ID
	ID *string `json:"id,omitempty"`

	MaxDevices *MaxDevices `json:"maxDevices,omitempty"`

	Name *string `json:"name,omitempty"`

	UserTrafficProfile *common.GenericRef `json:"userTrafficProfile,omitempty"`

	// VlanID
	// vlan id
	VlanID *int `json:"vlanId,omitempty"`

	VlanPooling *common.GenericRef `json:"vlanPooling,omitempty"`
}

type ModifySubscriptionPackage struct {
	Description *string `json:"description,omitempty"`

	// DomainID
	// Domain Id
	DomainID *string `json:"domainId,omitempty"`

	// ExpirationInterval
	// Expiration interval
	ExpirationInterval *string `json:"expirationInterval,omitempty"`

	// ExpirationValue
	// Expiration value
	ExpirationValue *int `json:"expirationValue,omitempty"`

	// ID
	// ID
	ID *string `json:"id,omitempty"`

	Name *string `json:"name,omitempty"`
}

type ModifyUser struct {
	// Address
	// Address
	Address *string `json:"address,omitempty"`

	// City
	// City
	City *string `json:"city,omitempty"`

	// CountryName
	// Country
	CountryName *string `json:"countryName,omitempty"`

	// CountryShortName
	// Country
	CountryShortName *string `json:"countryShortName,omitempty"`

	// DomainID
	// Domain Id
	DomainID *string `json:"domainId,omitempty"`

	// Email
	// Email
	Email *string `json:"email,omitempty"`

	// FirstName
	// First name
	FirstName *string `json:"firstName,omitempty"`

	// ID
	// ID
	ID *string `json:"id,omitempty"`

	// IsDisabled
	// Is Disabled
	IsDisabled *string `json:"isDisabled,omitempty"`

	// LastName
	// Last Name
	LastName *string `json:"lastName,omitempty"`

	// Password
	// Password
	Password *string `json:"password,omitempty"`

	// Phone
	// Phone
	Phone *string `json:"phone,omitempty"`

	// Remark
	// Remark
	Remark *string `json:"remark,omitempty"`

	// State
	// State
	State *string `json:"state,omitempty"`

	SubscriberPackage *common.GenericRef `json:"subscriberPackage,omitempty"`

	// ZipCode
	// Zip Code
	ZipCode *string `json:"zipCode,omitempty"`
}

type PackageConfiguration struct {
	// PackageExpiration
	// Package expiration interval and value
	PackageExpiration *string `json:"packageExpiration,omitempty"`

	SubscriberPackage *common.GenericRef `json:"subscriberPackage,omitempty"`
}

type PackageList struct {
	FirstIndex *int `json:"firstIndex,omitempty"`

	HasMore *bool `json:"hasMore,omitempty"`

	List []*PackageConfiguration `json:"list,omitempty"`

	TotalCount *int `json:"totalCount,omitempty"`
}

type PassValidFor struct {
	ExpirationUnit *string `json:"expirationUnit,omitempty"`

	ExpirationValue *int `json:"expirationValue,omitempty"`
}

type QueryCriteria struct {
}

type SessionDuration struct {
	RequireLoginAgain *bool `json:"requireLoginAgain,omitempty"`

	SessionUnit *string `json:"sessionUnit,omitempty"`

	SessionValue *int `json:"sessionValue,omitempty"`
}

type SubscriptionPackage struct {
	// CreateDateTime
	// Timestamp of being created
	CreateDateTime *int `json:"createDateTime,omitempty"`

	// CreatorID
	// Creator ID
	CreatorID *string `json:"creatorId,omitempty"`

	// CreatorUsername
	// Creator Name
	CreatorUsername *string `json:"creatorUsername,omitempty"`

	Description *string `json:"description,omitempty"`

	// DomainID
	// identifier of the domain
	DomainID *string `json:"domainId,omitempty"`

	// ExpirationInterval
	// Expiration interval
	ExpirationInterval *string `json:"expirationInterval,omitempty"`

	// ExpirationValue
	// Expiration value
	ExpirationValue *int `json:"expirationValue,omitempty"`

	// ModifiedDateTime
	// Timestamp of being modified
	ModifiedDateTime *int `json:"modifiedDateTime,omitempty"`

	// ModifierID
	// Modifier ID
	ModifierID *string `json:"modifierId,omitempty"`

	// ModifierUsername
	// Modifier Name
	ModifierUsername *string `json:"modifierUsername,omitempty"`

	Name *string `json:"name,omitempty"`
}

type SubscriptionPackageList struct {
	Extra *common.RBACMetadata `json:"extra,omitempty"`

	FirstIndex *int `json:"firstIndex,omitempty"`

	HasMore *bool `json:"hasMore,omitempty"`

	List []*SubscriptionPackageListType `json:"list,omitempty"`

	TotalCount *int `json:"totalCount,omitempty"`
}

type SubscriptionPackageListType struct {
	Description *string `json:"description,omitempty"`

	// DomainID
	// identifier of the domain
	DomainID *string `json:"domainId,omitempty"`

	// ExpirationInterval
	// Expiration interval
	ExpirationInterval *string `json:"expirationInterval,omitempty"`

	// ExpirationValue
	// Expiration value
	ExpirationValue *int `json:"expirationValue,omitempty"`

	// ID
	// the identifier of the subscription package
	ID *string `json:"id,omitempty"`

	Name *string `json:"name,omitempty"`
}

type UserConfiguration struct {
	// Address
	// Address
	Address *string `json:"address,omitempty"`

	// City
	// City
	City *string `json:"city,omitempty"`

	// CountryName
	// Country
	CountryName *string `json:"countryName,omitempty"`

	// CountryShortName
	// Country
	CountryShortName *string `json:"countryShortName,omitempty"`

	// CreateDateTime
	// Timestamp of being created
	CreateDateTime *int `json:"createDateTime,omitempty"`

	// CreatorID
	// Creator ID
	CreatorID *string `json:"creatorId,omitempty"`

	// CreatorUsername
	// Creator Name
	CreatorUsername *string `json:"creatorUsername,omitempty"`

	CredentialsGuestPassDto *UserConfigurationCredentialsGuestPassDtoType `json:"credentialsGuestPassDto,omitempty"`

	// Email
	// Email
	Email *string `json:"email,omitempty"`

	// FirstName
	// First name
	FirstName *string `json:"firstName,omitempty"`

	// IsDisabled
	// Is Disabled
	IsDisabled *string `json:"isDisabled,omitempty"`

	// LastName
	// Last Name
	LastName *string `json:"lastName,omitempty"`

	// ModifiedDateTime
	// Timestamp of being modified
	ModifiedDateTime *int `json:"modifiedDateTime,omitempty"`

	// ModifierID
	// Modifier ID
	ModifierID *string `json:"modifierId,omitempty"`

	// ModifierUsername
	// Modifier Name
	ModifierUsername *string `json:"modifierUsername,omitempty"`

	// PackageExpirationDate
	// Package Expiration Date
	PackageExpirationDate *int `json:"packageExpirationDate,omitempty"`

	// PackageExpirationInterval
	// Package Expiration Interval
	PackageExpirationInterval *string `json:"packageExpirationInterval,omitempty"`

	// PackageExpirationValue
	// Package Expiration Value
	PackageExpirationValue *int `json:"packageExpirationValue,omitempty"`

	// PackageStatus
	// Package Status
	PackageStatus *string `json:"packageStatus,omitempty"`

	// Phone
	// Phone
	Phone *string `json:"phone,omitempty"`

	// Remark
	// Remark
	Remark *string `json:"remark,omitempty"`

	// State
	// State
	State *string `json:"state,omitempty"`

	SubscriberPackage *common.GenericRef `json:"subscriberPackage,omitempty"`

	// UserName
	// User Name
	UserName *string `json:"userName,omitempty"`

	UsernamePasswordCredentialsImplDto *UsernamePasswordCredentialsImplDto `json:"usernamePasswordCredentialsImplDto,omitempty"`

	// ZipCode
	// Zip Code
	ZipCode *string `json:"zipCode,omitempty"`
}

type UserConfigurationCredentialsGuestPassDtoType struct {
	// AuthenticationMethod
	// Authentication method of credential
	AuthenticationMethod *string `json:"authenticationMethod,omitempty"`

	// AutoGeneratePassword
	// Pass generation
	AutoGeneratePassword *bool `json:"autoGeneratePassword,omitempty"`

	Comment *string `json:"comment,omitempty"`

	// CreationDate
	// Creation Date
	CreationDate *int `json:"creationDate,omitempty"`

	// CreatorID
	// Creator ID
	CreatorID *string `json:"creatorId,omitempty"`

	// DisplayName
	// filter identity user list by display name
	DisplayName *string `json:"displayName,omitempty"`

	// DomainID
	// identifier of the domain
	DomainID *string `json:"domainId,omitempty"`

	// ExpirationDate
	// Expiration date and time
	ExpirationDate *string `json:"expirationDate,omitempty"`

	ExpirationUnit *string `json:"expirationUnit,omitempty"`

	ExpirationValue *int `json:"expirationValue,omitempty"`

	ExpireAfterIfNotUsed *int `json:"expireAfterIfNotUsed,omitempty"`

	// GuestExpiration
	// Expiration time of guest pass
	GuestExpiration *int `json:"guestExpiration,omitempty"`

	// Key
	// Key of this guest pass
	Key *string `json:"key,omitempty"`

	// LoginPassword
	// Login Password
	LoginPassword *string `json:"loginPassword,omitempty"`

	MacAddressList []string `json:"macAddressList,omitempty"`

	// MaxDevices
	// Maximum number of allowed device
	MaxDevices *int `json:"maxDevices,omitempty"`

	// ServiceProviderID
	// Service Provider Id
	ServiceProviderID *string `json:"serviceProviderId,omitempty"`

	SessionUnit *string `json:"sessionUnit,omitempty"`

	SessionValue *int `json:"sessionValue,omitempty"`

	// UserKey
	// user ID of the identity guest pass
	UserKey *string `json:"userKey,omitempty"`

	// UserName
	// Username of this guest pass
	UserName *string `json:"userName,omitempty"`

	// WLAN
	// WLAN Id
	WLAN *string `json:"wlan,omitempty"`

	// WLANName
	// WLAN Name
	WLANName *string `json:"wlanName,omitempty"`
}

type UserList struct {
	Extra *common.RBACMetadata `json:"extra,omitempty"`

	FirstIndex *int `json:"firstIndex,omitempty"`

	HasMore *bool `json:"hasMore,omitempty"`

	List []*IdentityUserSummary `json:"list,omitempty"`

	TotalCount *int `json:"totalCount,omitempty"`
}

type UsernamePasswordCredentialsImplDto struct {
	// AuthenticationMethod
	// Authentication Method
	AuthenticationMethod *string `json:"authenticationMethod,omitempty"`

	AuthenticationServerConfig *AuthenticationServerConfig `json:"authenticationServerConfig,omitempty"`

	// CreationDate
	// Creation Date
	CreationDate *int `json:"creationDate,omitempty"`

	// ExpirationDate
	// Expiration Date
	ExpirationDate *int `json:"expirationDate,omitempty"`

	// Key
	// identifier of the UsernamePasswordCredentialsImplDto
	Key *string `json:"key,omitempty"`

	// LoginName
	// Login Name
	LoginName *string `json:"loginName,omitempty"`

	// LoginPassword
	// Login Password
	LoginPassword *string `json:"loginPassword,omitempty"`

	// PasswordCreation
	// Creation Date of Password
	PasswordCreation *string `json:"passwordCreation,omitempty"`

	// PasswordExpiration
	// Expiration Date of Password
	PasswordExpiration *string `json:"passwordExpiration,omitempty"`

	// ServiceProviderID
	// Service Provider Id
	ServiceProviderID *string `json:"serviceProviderId,omitempty"`
}
