package identity

// API Version: v8_0

type AaaServer struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type AaaServerList struct {
	FirstIndex *int         `json:"firstIndex,omitempty"`
	HasMore    *bool        `json:"hasMore,omitempty"`
	List       []*AaaServer `json:"list,omitempty"`
	TotalCount *int         `json:"totalCount,omitempty"`
}

type AuthenticationServerConfig struct {
	AUTHENTICATIONSERVERID   *string `json:"AUTHENTICATION_SERVER_ID,omitempty"`
	AUTHENTICATIONSERVERNAME *string `json:"AUTHENTICATION_SERVER_NAME,omitempty"`
	AUTHENTICATIONSERVERTYPE *string `json:"AUTHENTICATION_SERVER_TYPE,omitempty"`
	ID                       *string `json:"id,omitempty"`
	Local                    *bool   `json:"local,omitempty"`
	Name                     *string `json:"name,omitempty"`
	Type                     *string `json:"type,omitempty"`
}

type CountryList struct {
	FirstIndex *int              `json:"firstIndex,omitempty"`
	HasMore    *bool             `json:"hasMore,omitempty"`
	List       []*CountrySummary `json:"list,omitempty"`
	TotalCount *int              `json:"totalCount,omitempty"`
}

type CountrySummary struct {
	CountryName      *string `json:"countryName,omitempty"`
	CountryShortName *string `json:"countryShortName,omitempty"`
}

type CreateIdentityGuestPass struct {
	AutoGeneratedPassword *bool              `json:"autoGeneratedPassword,omitempty"`
	DomainID              *string            `json:"domainId,omitempty"`
	GuestName             *string            `json:"guestName,omitempty"`
	MaxDevices            *MaxDevices        `json:"maxDevices,omitempty"`
	NumberOfPasses        *int               `json:"numberOfPasses,omitempty"`
	PassEffectSince       *string            `json:"passEffectSince,omitempty"`
	PassUseDays           *int               `json:"passUseDays,omitempty"`
	PassValidFor          *PassValidFor      `json:"passValidFor,omitempty"`
	PassValue             *string            `json:"passValue,omitempty"`
	Remarks               *string            `json:"remarks,omitempty"`
	SessionDuration       *SessionDuration   `json:"sessionDuration,omitempty"`
	WLAN                  *common.GenericRef `json:"wlan,omitempty"`
	Zone                  *common.GenericRef `json:"zone,omitempty"`
}

type CreateIdentityUserRole struct {
	Description        *string            `json:"description,omitempty"`
	DomainID           *string            `json:"domainId,omitempty"`
	MaxDevices         *MaxDevices        `json:"maxDevices,omitempty"`
	Name               *string            `json:"name,omitempty"`
	UserTrafficProfile *common.GenericRef `json:"userTrafficProfile,omitempty"`
	VlanID             *int               `json:"vlanId,omitempty"`
	VlanPooling        *common.GenericRef `json:"vlanPooling,omitempty"`
}

type CreateSubscriptionPackage struct {
	Description        *string `json:"description,omitempty"`
	DomainID           *string `json:"domainId,omitempty"`
	ExpirationInterval *string `json:"expirationInterval,omitempty"`
	ExpirationValue    *int    `json:"expirationValue,omitempty"`
	Name               *string `json:"name,omitempty"`
}

type CreateUser struct {
	Address           *string            `json:"address,omitempty"`
	City              *string            `json:"city,omitempty"`
	CountryName       *string            `json:"countryName,omitempty"`
	CountryShortName  *string            `json:"countryShortName,omitempty"`
	DomainID          *string            `json:"domainId,omitempty"`
	Email             *string            `json:"email,omitempty"`
	FirstName         *string            `json:"firstName,omitempty"`
	IsDisabled        *string            `json:"isDisabled,omitempty"`
	LastName          *string            `json:"lastName,omitempty"`
	Password          *string            `json:"password,omitempty"`
	Phone             *string            `json:"phone,omitempty"`
	Remark            *string            `json:"remark,omitempty"`
	State             *string            `json:"state,omitempty"`
	SubscriberPackage *common.GenericRef `json:"subscriberPackage,omitempty"`
	UserName          *string            `json:"userName,omitempty"`
	ZipCode           *string            `json:"zipCode,omitempty"`
}

type DeleteBulk struct {
	IDList common.IDList `json:"idList,omitempty"`
}

type IdentityGuestPassConfiguration struct {
	AutoGeneratedPassword *bool              `json:"autoGeneratedPassword,omitempty"`
	DomainID              *string            `json:"domainId,omitempty"`
	ExpirationDate        *string            `json:"expirationDate,omitempty"`
	GeneratedOn           *string            `json:"generatedOn,omitempty"`
	GuestName             *string            `json:"guestName,omitempty"`
	ID                    *string            `json:"id,omitempty"`
	Key                   *string            `json:"key,omitempty"`
	MaxDevices            *MaxDevices        `json:"maxDevices,omitempty"`
	PassEffectSince       *string            `json:"passEffectSince,omitempty"`
	PassUseDays           *int               `json:"passUseDays,omitempty"`
	PassValidFor          *PassValidFor      `json:"passValidFor,omitempty"`
	Remarks               *string            `json:"remarks,omitempty"`
	SessionDuration       *SessionDuration   `json:"sessionDuration,omitempty"`
	Ssid                  *string            `json:"ssid,omitempty"`
	UserID                *string            `json:"userId,omitempty"`
	WLAN                  *common.GenericRef `json:"wlan,omitempty"`
	WLANRestrition        *string            `json:"wlanRestrition,omitempty"`
	Zone                  *common.GenericRef `json:"zone,omitempty"`
}

type IdentityGuestPassList struct {
	Extra      *common.RBACMetadata              `json:"extra,omitempty"`
	FirstIndex *int                              `json:"firstIndex,omitempty"`
	HasMore    *bool                             `json:"hasMore,omitempty"`
	List       []*IdentityGuestPassConfiguration `json:"list,omitempty"`
	TotalCount *int                              `json:"totalCount,omitempty"`
}

type IdentityList struct {
	Extra      *common.RBACMetadata `json:"extra,omitempty"`
	FirstIndex *int                 `json:"firstIndex,omitempty"`
	HasMore    *bool                `json:"hasMore,omitempty"`
	List       []*IdentityListType  `json:"list,omitempty"`
	TotalCount *int                 `json:"totalCount,omitempty"`
}

type IdentityListType struct {
	CreateDateTime     *int               `json:"createDateTime,omitempty"`
	CreatorID          *string            `json:"creatorId,omitempty"`
	CreatorUsername    *string            `json:"creatorUsername,omitempty"`
	Description        *string            `json:"description,omitempty"`
	DomainID           *string            `json:"domainId,omitempty"`
	ID                 *string            `json:"id,omitempty"`
	MaxDevices         *MaxDevices        `json:"maxDevices,omitempty"`
	ModifiedDateTime   *int               `json:"modifiedDateTime,omitempty"`
	ModifierID         *string            `json:"modifierId,omitempty"`
	ModifierUsername   *string            `json:"modifierUsername,omitempty"`
	Name               *string            `json:"name,omitempty"`
	UserTrafficProfile *common.GenericRef `json:"userTrafficProfile,omitempty"`
	VlanID             *int               `json:"vlanId,omitempty"`
	VlanPooling        *common.GenericRef `json:"vlanPooling,omitempty"`
}

type IdentityUserRole struct {
	CreateDateTime     *int               `json:"createDateTime,omitempty"`
	CreatorID          *string            `json:"creatorId,omitempty"`
	CreatorUsername    *string            `json:"creatorUsername,omitempty"`
	Description        *string            `json:"description,omitempty"`
	ID                 *string            `json:"id,omitempty"`
	MaxDevices         *MaxDevices        `json:"maxDevices,omitempty"`
	ModifiedDateTime   *int               `json:"modifiedDateTime,omitempty"`
	ModifierID         *string            `json:"modifierId,omitempty"`
	ModifierUsername   *string            `json:"modifierUsername,omitempty"`
	Name               *string            `json:"name,omitempty"`
	UserTrafficProfile *common.GenericRef `json:"userTrafficProfile,omitempty"`
	VlanID             *int               `json:"vlanId,omitempty"`
	VlanPooling        *common.GenericRef `json:"vlanPooling,omitempty"`
}

type IdentityUserSummary struct {
	CreatedOn   *string `json:"createdOn,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	DomainID    *string `json:"domainId,omitempty"`
	ID          *string `json:"id,omitempty"`
	IsDisabled  *string `json:"isDisabled,omitempty"`
	UserName    *string `json:"userName,omitempty"`
	UserSource  *string `json:"userSource,omitempty"`
	UserType    *string `json:"userType,omitempty"`
}

type ImportIdentityGuestPass struct {
	DomainID        *string            `json:"domainId,omitempty"`
	MaxDevices      *MaxDevices        `json:"maxDevices,omitempty"`
	PassEffectSince *string            `json:"passEffectSince,omitempty"`
	PassUseDays     *int               `json:"passUseDays,omitempty"`
	PassValidFor    *PassValidFor      `json:"passValidFor,omitempty"`
	SessionDuration *SessionDuration   `json:"sessionDuration,omitempty"`
	WLAN            *common.GenericRef `json:"wlan,omitempty"`
	Zone            *common.GenericRef `json:"zone,omitempty"`
}

type MaxDevices struct {
	MaxDevicesAllowed *string `json:"maxDevicesAllowed,omitempty"`
	MaxDevicesNumber  *int    `json:"maxDevicesNumber,omitempty"`
}

type ModifyIdentityUserRole struct {
	Description        *string            `json:"description,omitempty"`
	DomainID           *string            `json:"domainId,omitempty"`
	ID                 *string            `json:"id,omitempty"`
	MaxDevices         *MaxDevices        `json:"maxDevices,omitempty"`
	Name               *string            `json:"name,omitempty"`
	UserTrafficProfile *common.GenericRef `json:"userTrafficProfile,omitempty"`
	VlanID             *int               `json:"vlanId,omitempty"`
	VlanPooling        *common.GenericRef `json:"vlanPooling,omitempty"`
}

type ModifySubscriptionPackage struct {
	Description        *string `json:"description,omitempty"`
	DomainID           *string `json:"domainId,omitempty"`
	ExpirationInterval *string `json:"expirationInterval,omitempty"`
	ExpirationValue    *int    `json:"expirationValue,omitempty"`
	ID                 *string `json:"id,omitempty"`
	Name               *string `json:"name,omitempty"`
}

type ModifyUser struct {
	Address           *string            `json:"address,omitempty"`
	City              *string            `json:"city,omitempty"`
	CountryName       *string            `json:"countryName,omitempty"`
	CountryShortName  *string            `json:"countryShortName,omitempty"`
	DomainID          *string            `json:"domainId,omitempty"`
	Email             *string            `json:"email,omitempty"`
	FirstName         *string            `json:"firstName,omitempty"`
	ID                *string            `json:"id,omitempty"`
	IsDisabled        *string            `json:"isDisabled,omitempty"`
	LastName          *string            `json:"lastName,omitempty"`
	Password          *string            `json:"password,omitempty"`
	Phone             *string            `json:"phone,omitempty"`
	Remark            *string            `json:"remark,omitempty"`
	State             *string            `json:"state,omitempty"`
	SubscriberPackage *common.GenericRef `json:"subscriberPackage,omitempty"`
	ZipCode           *string            `json:"zipCode,omitempty"`
}

type PackageConfiguration struct {
	PackageExpiration *string            `json:"packageExpiration,omitempty"`
	SubscriberPackage *common.GenericRef `json:"subscriberPackage,omitempty"`
}

type PackageList struct {
	FirstIndex *int                    `json:"firstIndex,omitempty"`
	HasMore    *bool                   `json:"hasMore,omitempty"`
	List       []*PackageConfiguration `json:"list,omitempty"`
	TotalCount *int                    `json:"totalCount,omitempty"`
}

type PassValidFor struct {
	ExpirationUnit  *string `json:"expirationUnit,omitempty"`
	ExpirationValue *int    `json:"expirationValue,omitempty"`
}

type QueryCriteria struct {
}

type SessionDuration struct {
	RequireLoginAgain *bool   `json:"requireLoginAgain,omitempty"`
	SessionUnit       *string `json:"sessionUnit,omitempty"`
	SessionValue      *int    `json:"sessionValue,omitempty"`
}

type SubscriptionPackage struct {
	CreateDateTime     *int    `json:"createDateTime,omitempty"`
	CreatorID          *string `json:"creatorId,omitempty"`
	CreatorUsername    *string `json:"creatorUsername,omitempty"`
	Description        *string `json:"description,omitempty"`
	DomainID           *string `json:"domainId,omitempty"`
	ExpirationInterval *string `json:"expirationInterval,omitempty"`
	ExpirationValue    *int    `json:"expirationValue,omitempty"`
	ModifiedDateTime   *int    `json:"modifiedDateTime,omitempty"`
	ModifierID         *string `json:"modifierId,omitempty"`
	ModifierUsername   *string `json:"modifierUsername,omitempty"`
	Name               *string `json:"name,omitempty"`
}

type SubscriptionPackageList struct {
	Extra      *common.RBACMetadata           `json:"extra,omitempty"`
	FirstIndex *int                           `json:"firstIndex,omitempty"`
	HasMore    *bool                          `json:"hasMore,omitempty"`
	List       []*SubscriptionPackageListType `json:"list,omitempty"`
	TotalCount *int                           `json:"totalCount,omitempty"`
}

type SubscriptionPackageListType struct {
	Description        *string `json:"description,omitempty"`
	DomainID           *string `json:"domainId,omitempty"`
	ExpirationInterval *string `json:"expirationInterval,omitempty"`
	ExpirationValue    *int    `json:"expirationValue,omitempty"`
	ID                 *string `json:"id,omitempty"`
	Name               *string `json:"name,omitempty"`
}

type UserConfiguration struct {
	Address                            *string                                       `json:"address,omitempty"`
	City                               *string                                       `json:"city,omitempty"`
	CountryName                        *string                                       `json:"countryName,omitempty"`
	CountryShortName                   *string                                       `json:"countryShortName,omitempty"`
	CreateDateTime                     *int                                          `json:"createDateTime,omitempty"`
	CreatorID                          *string                                       `json:"creatorId,omitempty"`
	CreatorUsername                    *string                                       `json:"creatorUsername,omitempty"`
	CredentialsGuestPassDto            *UserConfigurationCredentialsGuestPassDtoType `json:"credentialsGuestPassDto,omitempty"`
	Email                              *string                                       `json:"email,omitempty"`
	FirstName                          *string                                       `json:"firstName,omitempty"`
	IsDisabled                         *string                                       `json:"isDisabled,omitempty"`
	LastName                           *string                                       `json:"lastName,omitempty"`
	ModifiedDateTime                   *int                                          `json:"modifiedDateTime,omitempty"`
	ModifierID                         *string                                       `json:"modifierId,omitempty"`
	ModifierUsername                   *string                                       `json:"modifierUsername,omitempty"`
	PackageExpirationDate              *int                                          `json:"packageExpirationDate,omitempty"`
	PackageExpirationInterval          *string                                       `json:"packageExpirationInterval,omitempty"`
	PackageExpirationValue             *int                                          `json:"packageExpirationValue,omitempty"`
	PackageStatus                      *string                                       `json:"packageStatus,omitempty"`
	Phone                              *string                                       `json:"phone,omitempty"`
	Remark                             *string                                       `json:"remark,omitempty"`
	State                              *string                                       `json:"state,omitempty"`
	SubscriberPackage                  *common.GenericRef                            `json:"subscriberPackage,omitempty"`
	UserName                           *string                                       `json:"userName,omitempty"`
	UsernamePasswordCredentialsImplDto *UsernamePasswordCredentialsImplDto           `json:"usernamePasswordCredentialsImplDto,omitempty"`
	ZipCode                            *string                                       `json:"zipCode,omitempty"`
}

type UserConfigurationCredentialsGuestPassDtoType struct {
	AuthenticationMethod *string  `json:"authenticationMethod,omitempty"`
	AutoGeneratePassword *bool    `json:"autoGeneratePassword,omitempty"`
	Comment              *string  `json:"comment,omitempty"`
	CreationDate         *int     `json:"creationDate,omitempty"`
	CreatorID            *string  `json:"creatorId,omitempty"`
	DisplayName          *string  `json:"displayName,omitempty"`
	DomainID             *string  `json:"domainId,omitempty"`
	ExpirationDate       *string  `json:"expirationDate,omitempty"`
	ExpirationUnit       *string  `json:"expirationUnit,omitempty"`
	ExpirationValue      *int     `json:"expirationValue,omitempty"`
	ExpireAfterIfNotUsed *int     `json:"expireAfterIfNotUsed,omitempty"`
	GuestExpiration      *int     `json:"guestExpiration,omitempty"`
	Key                  *string  `json:"key,omitempty"`
	LoginPassword        *string  `json:"loginPassword,omitempty"`
	MacAddressList       []string `json:"macAddressList,omitempty"`
	MaxDevices           *int     `json:"maxDevices,omitempty"`
	ServiceProviderID    *string  `json:"serviceProviderId,omitempty"`
	SessionUnit          *string  `json:"sessionUnit,omitempty"`
	SessionValue         *int     `json:"sessionValue,omitempty"`
	UserKey              *string  `json:"userKey,omitempty"`
	UserName             *string  `json:"userName,omitempty"`
	WLAN                 *string  `json:"wlan,omitempty"`
	WLANName             *string  `json:"wlanName,omitempty"`
}

type UserList struct {
	Extra      *common.RBACMetadata   `json:"extra,omitempty"`
	FirstIndex *int                   `json:"firstIndex,omitempty"`
	HasMore    *bool                  `json:"hasMore,omitempty"`
	List       []*IdentityUserSummary `json:"list,omitempty"`
	TotalCount *int                   `json:"totalCount,omitempty"`
}

type UsernamePasswordCredentialsImplDto struct {
	AuthenticationMethod       *string                     `json:"authenticationMethod,omitempty"`
	AuthenticationServerConfig *AuthenticationServerConfig `json:"authenticationServerConfig,omitempty"`
	CreationDate               *int                        `json:"creationDate,omitempty"`
	ExpirationDate             *int                        `json:"expirationDate,omitempty"`
	Key                        *string                     `json:"key,omitempty"`
	LoginName                  *string                     `json:"loginName,omitempty"`
	LoginPassword              *string                     `json:"loginPassword,omitempty"`
	PasswordCreation           *string                     `json:"passwordCreation,omitempty"`
	PasswordExpiration         *string                     `json:"passwordExpiration,omitempty"`
	ServiceProviderID          *string                     `json:"serviceProviderId,omitempty"`
}
